### ISSUE TITLE
 Missing 2.33-x64-chromedriver

### ISSUE THREAD

**Issue by kaganvmz** [gemini-testing/hermione#197]
I've installed hermione and selenium after start command test the error is appeared  

```javascript
Error: Missing C:\repository\html_qoob\node_modules\selenium-standalone\.selenium\chromedriver\2.33-x64-chromedriver
[1]     at C:\repository\html_qoob\node_modules\selenium-standalone\lib\check-paths-existence.js:15:20
[1]     at FSReqWrap.cb [as oncomplete] (fs.js:313:19)
[1] selenium-standalone start exited with code 1
```
Could somebody help me to resolve this issue?

My **.hermione.config.js**

```javascript
module.exports = {
	gridUrl: 'http://localhost:4444/wd/hub',
    sets: {
        desktop: {
            files: 'tests/desktop'
        }
    },
    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
            }
        }
    }
};
```

My **packege.json**

```javascript
"scripts": {
        "test": "hermione",
        "start": "concurrently \"node server.js\" \"selenium-standalone start\""
},
```

```javascript
 "devDependencies": {
        "chromedriver": "^2.33.2",
        "concurrently": "^3.5.0",
        "grunt": "^0.4.5",
        "grunt-cli": "^1.2.0",
        "grunt-contrib-clean": "^1.0.0",
        "grunt-contrib-compress": "^1.3.0",
        "hermione": "^0.50.3",
        "load-grunt-tasks": "^3.5.0",
        "selenium-standalone": "^6.11.0"
    }
```

**Comment by sipayRT** [comment]
it's not hermione error but `selenium-standalone`. You should run `selenium-standalone install` to install driver. See [doc](https://www.npmjs.com/package/selenium-standalone)
And you dont need `chromedriver` deps at all

**Comment by kaganvmz** [comment]
@sipayRT I've seen doc and I used this command to install **selenium-standalone** and  when error was appeared I tried to install  **chromedriver**.

**Comment by j0tunn** [comment]
You should probably address to selenium-standalone team.
I see an issue like yours: https://github.com/vvo/selenium-standalone/issues/177
