### ISSUE TITLE
Error: Cannot read property '0' of undefined — test-collection.js

### ISSUE THREAD

**Issue by ruslanxdev** [gemini-testing/hermione#380]
If you give a non-existing `browserId` to `sortTests` it retrun error:
```
TypeError: Cannot read property '0' of undefined
    at TestCollection.getRootSuite (/Users/ruslankhh/work/web4-1/node_modules/hermione/lib/test-collection.js:19:52)
    at _.forEach (/Users/ruslankhh/work/web4-1/node_modules/hermione/lib/test-collection.js:25:31)
    at /Users/ruslankhh/work/web4-1/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/ruslankhh/work/web4-1/node_modules/lodash/lodash.js:3001:24)
    at /Users/ruslankhh/work/web4-1/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/Users/ruslankhh/work/web4-1/node_modules/lodash/lodash.js:9359:14)
    at TestCollection.eachRootSuite (/Users/ruslankhh/work/web4-1/node_modules/hermione/lib/test-collection.js:24:11)
    at Hermione.hermione.on (/Users/ruslankhh/work/web4-1/node_modules/@yandex-int/templar-runner/hermione.js:84:24)
    at emitOne (events.js:121:20)
    at Hermione.emit (events.js:211:7)
    at Hermione.readTests (/Users/ruslankhh/work/web4-1/node_modules/hermione/lib/hermione.js:75:18)
    at <anonymous>
```

**Comment by ruslankhh** [comment]
Я сам починю)
