### ISSUE TITLE
it.skip is undefined

### ISSUE THREAD

**Issue by vaseker** [gemini-testing/hermione#398]
Hello!

Hermione@2.4.0 have no `it.skip()` method, but `describe.skip()` works fine.

Example
```js
describe('desktop blocks', function () {
    hermione.only.in(/1350/);
    describe('index-maps-widget-in-fact', function () {
        it.skip('with-nowcast-and-pollen', async function () {...
```

Throws
```
TypeError: it.skip is not a function
    at Suite.<anonymous> (/Users/vaseker/Documents/www/weather-frontend/hermione/desktop/blocks/index-maps-widget-in-fact.js:32:12)
    at context.describe.context.context (/Users/vaseker/Documents/www/weather-frontend/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Suite.<anonymous> (/Users/vaseker/Documents/www/weather-frontend/hermione/desktop/blocks/index-maps-widget-in-fact.js:31:5)
    at context.describe.context.context (/Users/vaseker/Documents/www/weather-frontend/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Object.<anonymous> (/Users/vaseker/Documents/www/weather-frontend/hermione/desktop/blocks/index-maps-widget-in-fact.js:29:1)
```

**Comment by Hypnosphi** [comment]
Probably related: `hermione.skip` works only on suite level

**Comment by DudaGod** [comment]
Hello.

In version hermione@3.3.1 it does not reproduce.

> Probably related: hermione.skip.in(browserId) works only on suite level

Currently it works not only on suite level, but also on test level too.
