### ISSUE TITLE
Cannot call non W3C standard command while in W3C mode

### ISSUE THREAD

**Issue by mickaelperrin** [gemini-testing/hermione#448]
Hi, 

I tried to setup the test in the quick start of the Readme file, but it fails with the following error.

``` hermione
✘ github should find hermione [chromeXL:0d68119880c5497396505fc1ed96b7d8] - 1512ms
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0

1) github should find hermione
   in file tests/hermione/test.js

   chromeXL
     ✘ Error: unknown command: Cannot call non W3C standard command while in W3C mode (unknown command: Cannot call non W3C standard command while in W3C mode)
    at new RuntimeError (/home/node/.npm-global/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/home/node/.npm-global/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/build/lib/utils/RequestHandler.js:322:39)
    at Request.self.callback (/home/node/.npm-global/lib/node_modules/hermione/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/node/.npm-global/lib/node_modules/hermione/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/node/.npm-global/lib/node_modules/hermione/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

I tried to add the `w3cCompatible` to the .hermione.conf.js file but it doesn't change anything.

I use selenium and node in docker with the following images:
- node:8
- selenium/hub:3
- selenium/node-chrome-debug:3

Any idea what's wrong ?

Thanks,

**Comment by e-marfoeldi-carnect** [comment]
Check this out:
webdriverio/webdriverio#4073
