### ISSUE TITLE
Error when running tests in Firefox

### ISSUE THREAD

**Issue by web-padawan** [gemini-testing/hermione#483]
I'm getting the following error with Firefox on Windows in SauceLabs:

```console
   firefox
     ✘ Error: mouseMoveTo (mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SAUCE-WIN10', ip: '10.119.53.189', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SAUCE-WIN10', ip: '10.119.53.189', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
    at new RuntimeError (/Users/sergey/vaadin/vaadin-accordion/node_modules/@gemini-testing/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/Users/sergey/vaadin/vaadin-accordion/node_modules/@gemini-testing/webdriverio/build/lib/utils/RequestHandler.js:322:39)
    at Request.self.callback (/Users/sergey/vaadin/vaadin-accordion/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/Users/sergey/vaadin/vaadin-accordion/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (/Users/sergey/vaadin/vaadin-accordion/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Could it be related to the problem mentioned at gemini-testing/gemini#948?

Do you have any idea where the potential fix should be?

**Comment by huston007** [comment]
Try "resetCursor: false" option in `browsers.firefox` section of config:

```
...
    firefox: {
      resetCursor: false, // Prevents grid failure on performing "moveto" command
...
```

**Comment by web-padawan** [comment]
Thanks! Using `resetCursor: false` helped to get rid of the error.

**Comment by DudaGod** [comment]
@web-padawan Hello. What firefox version are you using?

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue.
