### ISSUE TITLE
TypeError: Cannot read property 'hermioneCtx' of undefined

### ISSUE THREAD

**Issue by coustoue** [gemini-testing/hermione#491]
Здравствуйте, 
при попытке выполнить последний тест (код ниже) 
вылетает ошибка
```
 ✘ TypeError: Cannot read property 'hermioneCtx' of undefined
    at TestRunner.run (C:\DATA\App\hermione\node_modules\hermione\lib\worker\runner\test-runner\index.js:29:34)        
    at Runner.runTest (C:\DATA\App\hermione\node_modules\hermione\lib\worker\runner\index.js:37:23)
    at Hermione.runTest (C:\DATA\App\hermione\node_modules\hermione\lib\worker\hermione.js:31:29)
    at syncConfig.then (C:\DATA\App\hermione\node_modules\hermione\lib\worker\hermione-facade.js:40:40)
    at tryCatcher (C:\DATA\App\hermione\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\DATA\App\hermione\node_modules\bluebird\js\release\promise.js:547:31)     
    at Promise._settlePromise (C:\DATA\App\hermione\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\DATA\App\hermione\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

```
Код:
```
const assert = require('assert')
const desireUrl='https://mail.ru/'
const selector = '#q'

function openPage(url) {
  it ('openPage - ' + url, function() {
    let msg = 'Wrong page: '
    return this.browser
      .url(url)
      .getUrl()
        .then((getUrl) => {
        if (url!==getUrl) assert.fail(msg + getUrl)
      })
  })
}

function setInput(selector, text) {
  it ('setInput - selector: ' + selector + (text.length > 0 ? ': ' + text : ''), function (){
    if (text===undefined) text='undefined'
    let msg = 'Text mismatch - '
    return this.browser
      .waitForVisible(selector, 5000)
      .setValue(selector, text)
      .getValue(selector)
        .then((value) => {
          if (!value===text) { assert.fail(msg + text + ':' + value) }
        })
  })
}

function randomString(length=4) {
  if (isNaN(length)) return ''
    else if (length < 0) return ''
    let rnd = ''
    while (rnd.length < length) rnd += Math.random().toString(36).substring(2)
    return rnd.substring(0, length)
  }

// hermione.skip.in('chrome', "It shouldn't work this way in Chrome")
describe('Mail.ru - const string', () => {
  openPage(desireUrl)
  let str =  'textg7l6'
  setInput(selector, str)
  console.log('typeof: ', typeof str, str)
})

// hermione.skip.in('chrome', "It shouldn't work this way in Chrome")
describe('Mail.ru - Math.random()', () => {
  openPage(desireUrl)
  let str =  Math.random()
  setInput(selector, str)
  console.log('typeof: ', typeof str, str)
})

// hermione.skip.in('chrome', "It shouldn't work this way in Chrome")
describe('Mail.ru - randomString()', () => {
  openPage(desireUrl)
  let str =  randomString()
  setInput(selector, str)
  console.log('typeof: ', typeof str, str)
})
```

в консоль выводятся следующие данные:
```
typeof:  string textg7l6
typeof:  number 0.09451411534056042
typeof:  string be95
```
непонятно где "криминал".

**Comment by DudaGod** [comment]
Привет.

Судя по этому сообщению:
> в консоль выводятся следующие данные:

Ты считаешь, что тесты в момент выполнения `console.log` уже выполнились. На самом деле этот лог вывелся при чтении тестов, то есть до их запуска.

Пришли пожалуйста минимально воспроизводимый кейс и свой `hermione` конфиг.

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue.

**Comment by coustoue** [comment]
в консоль вывел, чтобы было понятно, что передается в тесты.

тестовый проект здесь
https://github.com/coustoue/sandbox_hermione

**Comment by coustoue** [comment]
@DudaGod вопрос закрыт "на бумаге", но не закрыт на деле.
обстоятельства не позволили мне написать раньше

**Comment by DudaGod** [comment]
Я постараюсь дойти сегодня.

**Comment by DudaGod** [comment]
Проблема в том, что у тебя название теста для `describe('Mail.ru - randomString()' -> setInput(selector, str)` генерируется всегда новое. Когда master процесс гермионы читает тест он получает одно название и передает его child процессу. Тот в свою очередь тоже читает тест и получает совершенно другое название и в итоге падает.

Тебе нужно, чтобы название теста было идемпотентным и не менялось при каждом чтении.

**Comment by coustoue** [comment]
@DudaGod,  не понятен тезис на счет нового названия теста каждый раз.
а как тогда с тестом ` describe('Mail.ru - Math.random()' -> setInput(selector, str)`
там разве не генерируется каждый раз новое название?
эти два теста по сути идентичны

**Comment by DudaGod** [comment]
А извиняюсь, я ошибся строкой. Проблема в этом тесте:
```
// hermione.skip.in('chrome', "It shouldn't work this way in Chrome")
describe('Mail.ru - randomString()', () => {
  openPage(desireUrl)
  let str =  randomString()
  setInput(selector, str)
  console.log('typeof: ', typeof str, str)
})
```

У тебя в нем выполняется функция - `randomString`, которая каждый раз генерит новую строку и ты ее добавляешь в название теста. За счет чего при каждом его чтении название меняется.

**Comment by coustoue** [comment]
Насколько я понял проблема здесь
```
function setInput(selector, text) {
  it ('setInput - selector: ' + selector + (text.length > 0 ? ': ' + text : ''), function (){
...
```
@DudaGod пишет:
> генерируется всегда новое. Когда master процесс гермионы читает тест он получает одно название и передает его child процессу. Тот в свою очередь тоже читает тест и получает совершенно другое название и в итоге падает.

в случае с передачей числа часть `+ (text.length > 0 ? ': ' + text : '')` просто игнорируется

Спасибо, теперь все понятно!

**Comment by DudaGod** [comment]
Пожалуйста.
