### ISSUE TITLE
При указании сетов через wildcard запуск второго сьюта падает с ошибкой 

### ISSUE THREAD

**Issue by loudless** [gemini-testing/hermione#560]
Привет. 

Ситуация следующая: 
- версия Гермионы `3.11.0`
- есть три сьюта, расположены в папке `hermione/test-suites`
- есть конфиг `.hermione.conf.js`, в котором указан путь до сьютов: 
```js
    sets: {
        all: {
            files: 'hermione/test-suites/**/*hermione.ts'
        }
    },
```
- при запуске тестов Гермиона запускает первый из трёх сьютов, а на следующем падает с ошибкой:
```
chrome
   ✘ TypeError: Cannot assign to read only property 'browser' of object '#<Object>'
  at MochaTestParser._injectBrowserConfigurator (/Users/test/project/node_modules/hermione/lib/test-reader/mocha-test-parser.js:191:26)
  at MochaTestParser.loadFiles (/Users/test/project/node_modules/hermione/lib/test-reader/mocha-test-parser.js:162:14)
  at CachingTestParser._parse (/Users/test/project/node_modules/hermione/lib/worker/runner/caching-test-parser.js:55:14)
  at CachingTestParser.parse (/Users/test/project/node_modules/hermione/lib/worker/runner/caching-test-parser.js:29:28)
  at Runner.runTest (/Users/test/project/node_modules/hermione/lib/worker/runner/index.js:31:40)
  at Hermione.runTest (/Users/test/project/node_modules/hermione/lib/worker/hermione.js:31:29)
  at /Users/test/project/node_modules/hermione/lib/worker/hermione-facade.js:40:40
  at tryCatcher (/Users/test/project/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/test/project/node_modules/bluebird/js/release/promise.js:547:31)
  at Promise._settlePromise (/Users/test/project/node_modules/bluebird/js/release/promise.js:604:18)
  at Promise._settlePromiseCtx (/Users/test/project/node_modules/bluebird/js/release/promise.js:641:10)
  at _drainQueueStep (/Users/test/project/node_modules/bluebird/js/release/async.js:97:12)
  at _drainQueue (/Users/test/project/node_modules/bluebird/js/release/async.js:86:9)
  at Async._drainQueues (/Users/test/project/node_modules/bluebird/js/release/async.js:102:5)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/test/project/node_modules/bluebird/js/release/async.js:15:14)
  at processImmediate (internal/timers.js:461:21)
```

- если создавать отдельный файл `index.ts`, где импортировать все сьюты и указывать его в поле `files` — всё работает, но тогда нельзя указывать в командной строке конкретный сьют для запуска, приходится комментировать импорты в `index.ts`

Подскажите, пожалуйста, что я делаю не так.

**Comment by DudaGod** [comment]
Привет.

Можешь прислать свой конфиг и код теста для воспроизведения проблемы?

Судя по стектрейсу ошибка летит отсюда - https://github.com/gemini-testing/hermione/blob/v3.11.0/lib/test-reader/mocha-test-parser.js#L191. 

Судя по расширению файла у тебя код тестов на ts написан верно? При запуске тестов ты же подключаешь компилятор ts-node с помощью опции require? - https://github.com/gemini-testing/hermione/tree/v3.11.0#require-modules.
Кроме этого нужно указывать опцию `fileExtensions` - https://github.com/gemini-testing/hermione/tree/v3.11.0#fileextensions.

Единственная проблема, что сейчас подключаемый компилятор при запуске гермионы не подключается в worker-е. Исправляем это тут - https://github.com/gemini-testing/hermione/pull/558. Сегодня выкатим версию с исправлением.

**Comment by loudless** [comment]
Разобрался, проблема была в стороннем плагине, который перезаписывал browser на readonly-свойство. 

Код тестов на `TS`, используем пакет `ts-node/register` и кажется, что исправление в пулл-реквесте поможет писать тесты более удобно — сейчас приходится писать относительные пути к импортируемым модулям. 

Спасибо и прошу прощения за беспокойство.
