### ISSUE TITLE
При добавлении плагина аллюр возникает ошибка ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by nikaswoon** [gemini-testing/hermione#581]
плагин добавлен следующим образом
https://github.com/gemini-testing/hermione-allure-reporter#usage

имеющиеся зависимости:
`{
  "dependencies": {
    "chai": "^4.3.4",
    "hermione": "^4.1.4",
    "hermione-allure-reporter": "^1.5.1"
  }
}`

stdout:
`ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/user/project/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/user/project/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/user/project/node_modules/allure-js-commons/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/user/project/node_modules/allure-js-commons/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
`

**Comment by DudaGod** [comment]
Привет.

А ты же видел, что плагин hermione-allure-reporter depracated? Т.е. мы его больше не поддерживаем и не удивительно, что он не работает.

Предлагаю заюзать плагин html-reporter - https://github.com/gemini-testing/html-reporter. Мы его активно развиваем и он довольно удобный. Так же в нем есть режим gui, т.е. можно запускать тесты прямо из отчета.

**Comment by nikaswoon** [comment]
Привет!
ааа ну там так в уголочке написано что и не заметишь)
+ в документации на него ссылаетесь https://github.com/gemini-testing/hermione#plugins
Это вводит в заблуждение)

**Comment by DudaGod** [comment]
Хм, действительно. Не порядок. Сейчас поправлю. Спасибо.
