### ISSUE TITLE
Предполагается ли запуск тестов в BrowserStack?

### ISSUE THREAD

**Issue by nikaswoon** [gemini-testing/hermione#583]
Если да, то как прописать конфиг?
В документации говорится только о SauceLab

**Comment by DudaGod** [comment]
В доке browserstack-а можно найти как настроить - https://www.browserstack.com/docs/automate/selenium/migrate-existing-test-suites#overview.

В итоге нужно просто правильно выставить `gridUrl`. Например что-то типа такого:
```
// .hermione.conf.js
'use strict;

const userName = "YOUR_USERNAME";
const accessKey = "YOUR_ACCESS_KEY"

module.exports = {
  gridUrl: `https://${userName}:${accessKey}@hub-cloud.browserstack.com/wd/hub`;
  // ...
};
```

**Comment by xzhang147** [comment]
@DudaGod can you please show an example of a full config file? Blow is what I did but still not working on browserstack:

```
module.exports = {
    sets: {
        desktop: {
            files: 'test/hermione'
        }
    },

    gridUrl: `https://${keys.username}:${keys.accessKey}@hub-cloud.browserstack.com/wd/hub`,

    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
                version: '80'
            },
        },
    },
};
```
With error: Error: Failed to create session.

**Comment by DudaGod** [comment]
Try to set `browserVersion` instead `version` in `desiredCapabilities`.
If it doesn't help then try to run tests using this browser stack example - https://github.com/browserstack/webdriverio-browserstack with your `userName` and `accessKey`.

**Comment by xzhang147** [comment]
@DudaGod Thanks for your reply. Set `browserVersion` seems not working...

**Comment by DudaGod** [comment]
> Thanks for your reply. Set browserVersion seems not working...

What error are you getting? Are you sure that you have chrome@80 in your browserstack account?
I suggested to use this example - https://github.com/browserstack/webdriverio-browserstack in order to figured out where the problem: in hermione or in your browserstack account.

**Comment by xzhang147** [comment]
Here is my errors:
```
2021-08-16T17:36:36.069Z ERROR webdriver: RequestError: write EPROTO 4511010304:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at ClientRequest.<anonymous> (/.../node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/.../node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
✘ github should find hermione [chrome] - 0ms
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0

1) github should find hermione
   in file test/hermione/github.js

   chrome
     ✘ Error: Failed to create session.
write EPROTO 4511010304:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at Object.startWebDriverSession (/.../node_modules/webdriver/build/utils.js:68:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.newSession (/.../node_modules/webdriver/build/index.js:58:45)
    at async Object.remote (/.../node_modules/webdriverio/build/index.js:67:22)
    at async NewBrowser.init (/.../node_modules/hermione/lib/browser/browser.js:36:25)
    at async NewBrowser.init (/.../node_modules/hermione/lib/browser/new-browser.js:15:9)
    at async RegularTestRunner._getBrowser (/.../node_modules/hermione/lib/runner/test-runner/regular-test-runner.js:84:29)
    at async RegularTestRunner.run (/.../node_modules/hermione/lib/runner/test-runner/regular-test-runner.js:22:29)
    at async InsistantTestRunner.run (/.../node_modules/hermione/lib/runner/test-runner/insistant-test-runner.js:48:9)
    at async BrowserRunner._runTest (/.../node_modules/hermione/lib/runner/browser-runner.js:73:9)
```

**Comment by xzhang147** [comment]
@DudaGod May I ask when I am running Hermione with browerstack, do I still need to run `selenium-standalone start`?

**Comment by DudaGod** [comment]
> Here is my errors:

Looks like that the problem with ssl certificate. Try to change scheme of browserstak url from https to http.

> @DudaGod May I ask when I am running Hermione with browerstack, do I still need to run selenium-standalone start?

No, you don't, because hermione create browser session in browserstack cloud.

**Comment by xzhang147** [comment]
@DudaGod Thanks a lot! http works!

**Comment by DudaGod** [comment]
> приветствую! а можно ли каким-то другим способом исправить ошибку? Хотелось бы оперировать конф.данными по защищённому протоколу.

Тут проблема же в browserstack, что на их браузерах не стоит никаких ssl сертификатов. Возможно есть возможность поднести их на каждый свой браузер (нужно доку читать). Другие варианты:
- в desiredCapabilities выставлять `acceptInsecureCerts` (в разных браузерах по разному называется)
- ходить по http
