### ISSUE TITLE
Vertical scroll in mobile view is marked

### ISSUE THREAD

**Issue by IrinaDydy** [gemini-testing/hermione#634]
Добрый день!

Скриншотилка реагирует на незначительные отклонения положения вертикального скролла

![image](https://user-images.githubusercontent.com/44712585/158147961-466ec676-cfcd-47d6-9e76-b0c2269c59ef.png)

Подскажите, можно ли как-то скрыть (не учитывать при сравнении) полосу вертикального скролла в случае удалённого запуска тестов через ggr?

**Comment by DudaGod** [comment]
Привет.
Похоже что-то на страницу добавляется и скролл реагирует небольшим смещением ниже.

В твоем случае возможно достаточно просто переснять скриншот.

Какие есть варианты решения:
- не снимать всю страницу, а только необходимый блок или связку блоков
- выставить опцию [screenshotDelay](https://github.com/gemini-testing/hermione#screenshotDelay) в 600. За 600мс обычно скролл бар успевает скрыться
- отключить скролл с помощью плагина - https://github.com/gemini-testing/hermione-hide-scrollbars (работает только в хромах с поддержкой [CDP](https://chromedevtools.github.io/devtools-protocol/))
- перед снятием скриншота наложить на страницу невидимый элемент со смещением справа на необходимое количество пикселей, т.е. чтобы скроллбар не попадал на страницу.

**Comment by IrinaDydy** [comment]
Добрый день!

Было замечено, при попытке скрытия скролл бара через css:
var styleElement = document.createElement('style');
  styleElement.id = 'remove-scroll-style';
  styleElement.textContent = 'html{overflow:auto}' +
        'body::-webkit-scrollbar{display:none !important;}' +
        'body{overflow-y: scroll;overflow-x: hidden;}';
 document.body.appendChild(styleElement);

В частности, при добавлении html{overflow:auto} и с настройками 
compositeImage: true и assertViewOpts: { allowViewportOverflow: true }:

Тест выдаёт ошибку при снятии скриншота:
 Error: Out of the bounds
    at PngImg.crop (C:\Repos\ForHermione\Autotests\KL.CIWD.Autotests.Hermione\node_modules\png-img\index.js:71:19)
    at Image.crop (C:\Repos\ForHermione\Autotests\KL.CIWD.Autotests.Hermione\node_modules\gemini-core\lib\image\index.js:23:19)
    at Camera._cropToViewport (C:\Repos\ForHermione\Autotests\KL.CIWD.Autotests.Hermione\node_modules\gemini-core\lib\browser\camera\index.js:54:22)
    at C:\Repos\ForHermione\Autotests\KL.CIWD.Autotests.Hermione\node_modules\gemini-core\lib\browser\camera\index.js:25:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Browser.<anonymous> (C:\Repos\ForHermione\Autotests\KL.CIWD.Autotests.Hermione\node_modules\hermione\lib\browser\commands\assert-view\index.js:56:29)
    at async Browser.wrapCommandFn (C:\Repos\ForHermione\Autotests\KL.CIWD.Autotests.Hermione\node_modules\@wdio\utils\build\shim.js:137:29)

**Comment by DudaGod** [comment]
Привет.

Похоже падает при попытке кропнуть изображение. Можешь прислать пример теста на котором такая проблема воспроизводится?

**Comment by IrinaDydy** [comment]
Тест предельно простой, берём xpath для элемента на странице и делаем this.browser.assertView(`${path}`, elementXpath), просто что элемент, за частую, не помещается в высоту на страницу (как например лайаут), а снять скрин элемента требуется полностью, по этому использую compositeImage: true и assertViewOpts: { allowViewportOverflow: true }:

**Comment by DudaGod** [comment]
На словах должно работать. Но, чтобы понять проблему мне нужен код теста, который я бы мог запустить самостоятельно и понять в чем дело.

**Comment by DudaGod** [comment]
Закрываю, так как пример кода теста так и не был предоставлен.
