### ISSUE TITLE
Не устанавливается hermione на windows с версии 5.1.0

### ISSUE THREAD

**Issue by slaeme** [gemini-testing/hermione#665]
Версия 5.0.1 на Windows устанавливается

Версия 5.1.0 уже нет, проблемы при сборке png-img

Вижу что png-img был [обновлен до 4 мажора](https://github.com/gemini-testing/hermione/commit/58f3da8282970b5a09b6bc9c969298d0d8313bf9), [дифф](https://github.com/gemini-testing/hermione/compare/v5.0.1...v5.1.0).

Текст ошибки:
```
C:\test>npm i hermione@5.2.1
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> png-img@4.1.0 install C:\test\node_modules\png-img
> prebuild-install || npm run build-release

prebuild-install warn install No prebuilt binaries found (target=12.22.8 runtime=node arch=x64 libc= platform=win32)

> png-img@4.1.0 build-release C:\test\node_modules\png-img
> node-gyp rebuild --release

C:\test\node_modules\png-img>if not defined npm_config_node_gyp (node "C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "/m".
  png.c
  pngerror.c
  pngget.c
  pngmem.c
  pngpread.c
  pngread.c
  pngrio.c
  pngrtran.c
  pngrutil.c
  pngset.c
  pngtest.c
  pngtrans.c
  pngwio.c
  pngwrite.c
  pngwtran.c
  pngwutil.c
  arm_init.c
  filter_neon_intrinsics.c
  win_delay_load_hook.cc
  libpng.vcxproj -> C:\test\node_modules\png-img\build\Release\\libpng.lib
  adler32.c
  compress.c
  crc32.c
  deflate.c
  gzclose.c
  gzlib.c
  gzread.c
  gzwrite.c
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  win_delay_load_hook.cc
  zlib.vcxproj -> C:\test\node_modules\png-img\build\Release\\zlib.lib
  init.cc
  PngImgAdapter.cc
  PngImg.cc
  win_delay_load_hook.cc
  c:\test\node_modules\png-img\src\cpp\pngimgadapter.cc(82): error C2059: синтаксическая ошибка: . [C:\test\node_modules\png-img\build\png_img.vcxproj]
c:\test\node_modules\png-img\src\cpp\pngimgadapter.cc(86): error C2143: синтаксическая ошибка: отсутствие ";" перед "}" [C:\test\node_modules\png-img\build\p
ng_img.vcxproj]
c:\test\node_modules\png-img\src\cpp\pngimgadapter.cc(87): error C2059: синтаксическая ошибка: return [C:\test\node_modules\png-img\build\png_img.vcxproj]
c:\test\node_modules\png-img\src\cpp\pngimgadapter.cc(88): error C2059: синтаксическая ошибка: } [C:\test\node_modules\png-img\build\png_img.vcxproj]
c:\test\node_modules\png-img\src\cpp\pngimgadapter.cc(88): error C2143: синтаксическая ошибка: отсутствие ";" перед "}" [C:\test\node_modules\png-img\build\p
ng_img.vcxproj]
c:\test\node_modules\png-img\src\cpp\pngimgadapter.cc(91): error C2143: синтаксическая ошибка: отсутствие ";" перед "{" [C:\test\node_modules\png-img\build\p
ng_img.vcxproj]
c:\test\node_modules\png-img\src\cpp\pngimgadapter.cc(91): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого ти
па) [C:\test\node_modules\png-img\build\png_img.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\test\node_modules\png-img
gyp ERR! node -v v12.22.8
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! png-img@4.1.0 build-release: node-gyp rebuild --release
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png-img@4.1.0 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2022-10-06T06_20_13_719Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! png-img@4.1.0 install: prebuild-install || npm run build-release
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png-img@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2022-10-06T06_20_14_186Z-debug.log
```

**Comment by j0tunn** [comment]
Пофикшено в hermione@5.3.1
Для связности: https://github.com/gemini-testing/png-img/pull/77
