### ISSUE TITLE
httpTimeout of undefined at hermione@0.18.1

### ISSUE THREAD

**Issue by kbakba** [gemini-testing/hermione#95]
```
$ node -v
v5.1.0
$ npm -v
3.3.12
$ npm ls -depth 0
selenium@1.0.0 <CUT>
├── chai@3.5.0
├── hermione@0.18.1
└── selenium-standalone@5.9.0
```

```
$ npm test

> selenium@1.0.0 test <CUT>
> hermione

✘  "before all" hook [chrome] - 3ms
Total: 1 Passed: 0 Failed: 1 Pending: 0 Retries: 0

1)  "before all" hook
   in file undefined

   chrome
     ✘ TypeError: Cannot read property 'httpTimeout' of undefined
    at Browser._createSession (<CUT>/node_modules/hermione/lib/browser.js:68:58)
    at <CUT>/node_modules/hermione/lib/browser.js:28:45
    at Fulfilled_callInvoke [as callInvoke] (<CUT>/node_modules/q/q.js:1269:25)
    at Fulfilled_call [as call] (<CUT>/node_modules/q/q.js:1242:17)
    at Fulfilled_dispatch [as dispatch] (<CUT>/node_modules/q/q.js:1216:31)
    at Promise_dispatch_task (<CUT>/node_modules/q/q.js:978:28)
    at RawTask.call (<CUT>/node_modules/asap/asap.js:40:19)
    at flush (<CUT>/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
npm ERR! Test failed.  See above for more details.
```

hermione@0.18.0 - works correctly

**Comment by eGavr** [comment]
Hi!

Thank you for report. Can yo send your `.hermione.conf.js`, please ?

**Comment by kbakba** [comment]
```
$ cat .hermione.conf.js
var fs = require('fs');
var path = require('path');

module.exports = {
    specs: ['tests'],
    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        }
    }
};
```

**Comment by DudaGod** [comment]
@kbakba hello, can you try with new version - 0.18.2? We fixed this bug on this version.

**Comment by kbakba** [comment]
Thank you!
0.18.2 works fine!
